table _Medidas
	lineageTag: 9328caa6-d98e-4619-96f3-0c39bf7a54a2

	measure TotalAlunos = COUNTROWS(Alunos)
		lineageTag: 2af9734b-39ef-49e8-9def-692799d67bf0
		formatString: #,0

	measure AlunosEscolaPublica = CALCULATE([TotalAlunos], Alunos[TipoInstituicao] = "Pública")
		lineageTag: 41967a37-dafb-413a-b499-a90330eb494c
		formatString: #,0

	measure AlunosEscolaParticular = CALCULATE([TotalAlunos], Alunos[TipoInstituicao] = "Particular")
		lineageTag: bca6d13f-9da7-4d02-a5a6-afdad1df1244
		formatString: #,0

	measure PctEscolaPublica = DIVIDE([AlunosEscolaPublica], [TotalAlunos])
		lineageTag: 5725a261-1061-4f6b-9012-f037b7d034c5
		formatString: 0.0%

	measure RendaMediaSM = AVERAGE(Alunos[RendaSM_Aprox])
		lineageTag: 8a532e4d-1bc6-4703-9cd5-425c0df085da
		formatString: 0.0

	measure AlunosBaixaRenda = CALCULATE([TotalAlunos], Alunos[FaixaRendaOrdem] <= 3)
		lineageTag: 8abe1b27-eefe-41b3-804d-96766b390d0f
		formatString: #,0

	measure PctBaixaRenda = DIVIDE([AlunosBaixaRenda], [TotalAlunos])
		lineageTag: 678f17d1-7709-4a65-aaf7-7a066ffb89c1
		formatString: 0.0%

	measure PctSobreTotal = DIVIDE([TotalAlunos], CALCULATE([TotalAlunos], ALL(Alunos)))
		lineageTag: 2fe2290f-7a5b-4462-a3cf-cf7601bcfb2d
		formatString: 0.0%

	measure TotalComDeficiencia = CALCULATE([TotalAlunos], Alunos[TipoDeficiencia] <> "Sem Deficiência")
		lineageTag: b170ffd1-376e-4817-89c4-155bb16136f1
		formatString: #,0

	measure PctDeficienciaFisica = DIVIDE(CALCULATE([TotalAlunos], Alunos[TipoDeficiencia] = "Deficiência Física"), [TotalAlunos])
		lineageTag: 8c41d85b-56a5-49b4-ac3a-9f5e26fb6ef9
		formatString: 0.0%

	measure PctDeficienciaIntelectual = DIVIDE(CALCULATE([TotalAlunos], Alunos[TipoDeficiencia] = "Deficiência Intelectual"), [TotalAlunos])
		lineageTag: e94d9683-ab02-46b7-ad0e-1e9414ac432b
		formatString: 0.0%

	partition _Medidas = calculated
		source = {""}

	annotation PBI_Id = fd8de234-93b3-4ad1-b3d9-67ed58da84de
