table _Medidas
	lineageTag: 6dad1c2b-69fb-4934-bece-a45ffa120b32

	measure TotalAlunos = COUNTROWS(Alunos)
		formatString: #,0
		lineageTag: 048147be-0434-4a58-bd90-a66d1d214e7f

	measure AlunosEscolaPublica = CALCULATE([TotalAlunos], Alunos[TipoInstituicao] = "Pública")
		formatString: #,0
		lineageTag: 58f66e4a-2f76-420e-a28c-705100a1f021

	measure AlunosEscolaParticular = CALCULATE([TotalAlunos], Alunos[TipoInstituicao] = "Particular")
		formatString: #,0
		lineageTag: 56c0a1ea-d125-43a2-9c8e-48352dcdacd2

	measure PctEscolaPublica = DIVIDE([AlunosEscolaPublica], [TotalAlunos])
		formatString: 0.0%
		lineageTag: 6fbf4941-d463-44d6-b390-98c660c09ce2

	measure RendaMediaSM = AVERAGE(Alunos[RendaSM_Aprox])
		formatString: 0.0
		lineageTag: 2cc402d0-abba-46a5-9044-dc70213f906d

	measure AlunosBaixaRenda = CALCULATE([TotalAlunos], Alunos[FaixaRendaOrdem] <= 3)
		formatString: #,0
		lineageTag: 1b4c59e9-f926-4fb4-9879-7f32339186f3

	measure PctBaixaRenda = DIVIDE([AlunosBaixaRenda], [TotalAlunos])
		formatString: 0.0%
		lineageTag: 01adc179-86b3-460a-87eb-1f1e03011537

	measure PctSobreTotal = DIVIDE([TotalAlunos], CALCULATE([TotalAlunos], ALL(Alunos)))
		formatString: 0.0%
		lineageTag: c4ae9ee5-0f34-42bb-a073-4276783f8e9c

	column Value
		lineageTag: a4d3dba8-7247-469c-8faf-5857bfd92856
		isNameInferred
		sourceColumn: [Value]

	partition _Medidas = calculated
		source = {""}

	annotation PBI_Id = d464c953-889f-4bd4-96b3-a73d7bcd8c81

